server:
    host: None

shapes:
    - [
        [1, 1, 0] # Z
        [0, 1, 1]
    ]
    - [
        [0, 1, 1] # S
        [1, 1, 0]
    ]
    - [
        [1, 1, 1] # T
        [0, 1, 0]
    ]
    - [
        [1, 1] # O
        [1, 1]
    ]
    - [
        [1] # I
        [1]
        [1]
        [1]
    ]
    - [
        [1, 0] # L
        [1, 0]
        [1, 1]
    ]
    - [
        [0, 1] # J
        [0, 1]
        [1, 1]
    ]