server:
    host: None

shapes:
    -
        color: 0xff0000 # red
        scheme: [
            [1, 1, 0], # Z
            [0, 1, 1]
        ]

    -
        color: 0x00ff00 # green
        scheme: [
            [0, 1, 1], # S
            [1, 1, 0]
        ]

    -
        color: 0x0000ff # blue
        scheme: [
            [ 0, 1 ], # J
            [ 0, 1 ],
            [ 1, 1 ]
            ]
    -
        color: 0xff5f1f # orange
        scheme: [
            [ 1, 0 ], # L
            [ 1, 0 ],
            [ 1, 1 ]
            ]
    -
        color: 0xffff00 # yellow
        scheme: [
            [ 1, 1 ], # O
            [ 1, 1 ]
            ]

    -
        color: 0x00ffff # cyan
        scheme: [
            [ 1 ], # I
            [ 1 ],
            [ 1 ],
            [ 1 ]
            ]

    -
        color: 0xff00ff # magenta
        scheme: [
            [ 1, 1, 1 ], # T
            [ 0, 1, 0 ]
            ]



gamemodes:
    -
        name: "Classic"
        id: "classic"
        default_speed: 1
        speed_multiplier: 1.5
        speed_increment_every: 10
        max_speed: 10
        shapes: [0, 1, 2, 3, 4, 5, 6] # represents the index of the shape in the shapes list
        invisible: false
        xp_multiplier: 1
    -
        name: "Invisible"
        id: "invisible"
        default_speed: 1
        speed_multiplier: 1.30
        max_speed: 7
        speed_increment_every: 12
        shapes: [0, 1, 2, 3, 4, 5, 6]
        invisible: true
        xp_multiplier: 1.5

    -
        name: "Blitz"
        id: "blitz"
        default_speed: 1.2
        speed_multiplier: 1.10
        max_speed: 25
        speed_increment_every: 1
        shapes: [0, 1, 2, 3, 4, 5, 6]
        invisible: false
        xp_multiplier: 2.5
