server:
    host: "https://tetris.cloud.voltis.me"

shapes:
    -
        color: [40, 174, 0]
        scheme: [
            [1, 1, 0], # Z
            [0, 1, 1]
        ]

    -
        color: [255, 0, 0]
        scheme: [
            [0, 1, 1], # S
            [1, 1, 0]
        ]

    -
        color: [252, 62, 189]
        scheme: [
            [ 0, 1 ], # J
            [ 0, 1 ],
            [ 1, 1 ]
            ]
    -
        color: [255, 145, 0]
        scheme: [
            [ 1, 0 ], # L
            [ 1, 0 ],
            [ 1, 1 ]
            ]
    -
        color: [255, 255, 0]
        scheme: [
            [ 1, 1 ], # O
            [ 1, 1 ]
            ]

    -
        color: [0, 255, 239]
        scheme: [
            [ 1 ], # I
            [ 1 ],
            [ 1 ],
            [ 1 ]
            ]

    -
        color: [154, 77, 255]
        scheme: [
            [ 1, 1, 1 ], # T
            [ 0, 1, 0 ]
            ]

    # New pieces

    -
        color: [0, 17, 255]
        scheme: [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1]     # slash
            ]

    -
        color: [255, 255, 255]
        scheme: [
            [0, 1, 0],
            [1, 1, 1],
            [0, 1, 0]   # + sign
            ]

    -
        color: [0, 255, 154]
        scheme: [
            [1, 1, 0],
            [0, 1, 0],
            [0, 1, 1]    # long z
            ]
    -
        color: [98, 52, 0]
        scheme: [
            [1, 0, 1],
            [1, 1, 1],  # U
            ]


gamemodes:
    -
        name: "Classic"
        id: "classic"
        default_speed: 1
        speed_multiplier: 1.40
        speed_increment_every: 8
        max_speed: 25
        shapes: [0, 1, 2, 3, 4, 5, 6] # represents the index of the shape in the shapes list
        invisible: 0
    -
        name: "One Color"
        id: "one_color"
        default_speed: 1
        speed_multiplier: 1.32
        max_speed: 15
        speed_increment_every: 8
        shapes: [0, 1, 2, 3, 4, 5, 6]
        invisible: 1

    -
        name: "Blitz"
        id: "blitz"
        default_speed: 1.2
        speed_multiplier: 1.20
        max_speed: 45
        speed_increment_every: 2
        shapes: [0, 1, 2, 3, 4, 5, 6]
        invisible: 0

    -
        name: "One Piece"
        id: "one_piece"
        default_speed: 1
        speed_multiplier: 1.5
        speed_increment_every: 5
        max_speed: 25
        shapes: [0]
        invisible: 0

    - name: "Extended"
      id: "extended"
      default_speed: 1
      speed_multiplier: 1.5
      speed_increment_every: 7
      max_speed: 25
      shapes: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      invisible: 0